const { contextBridge, ipcRenderer, clipboard } = require('electron');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { decodeAnimation } = require('./lib/gif-decoder');
const assetRoot = path.join(__dirname, ipcRenderer.sendSync('get-is-packaged') ? '../assets' : 'assets');
const api = { assetRoot,
 decodeAnimation: filename => { if (typeof filename !== 'string' || !/^[\w -]+\.gif$/i.test(filename)) throw new Error('Invalid animation asset'); return decodeAnimation(path.join(assetRoot,filename)); },
 fileUrl: filename => pathToFileURL(filename).href,
 copyDiagnostics: value => { if (typeof value !== 'string' || value.length > 100000) throw new Error('Invalid diagnostic text'); clipboard.writeText(value); },
};
api.askOpenai = (...args) => ipcRenderer.invoke('ask-openai',...args);
api.cancelTimer = (...args) => ipcRenderer.invoke('cancel-timer',...args);
api.checkEverything = (...args) => ipcRenderer.invoke('check-everything',...args);
api.checkForUpdates = (...args) => ipcRenderer.invoke('check-for-updates',...args);
api.createCalendarEvent = (...args) => ipcRenderer.invoke('create-calendar-event',...args);
api.evaVoiceStatus = (...args) => ipcRenderer.invoke('eva-voice-status',...args);
api.findApplication = (...args) => ipcRenderer.invoke('find-application',...args);
api.getAccentColor = (...args) => ipcRenderer.invoke('get-accent-color',...args);
api.getAppVersion = (...args) => ipcRenderer.invoke('get-app-version',...args);
api.getEdgeVoices = (...args) => ipcRenderer.invoke('get-edge-voices',...args);
api.getHotkeyStatus = (...args) => ipcRenderer.invoke('get-hotkey-status',...args);
api.getNotebook = (...args) => ipcRenderer.invoke('get-notebook',...args);
api.getReminders = (...args) => ipcRenderer.invoke('get-reminders',...args);
api.getSettings = (...args) => ipcRenderer.invoke('get-settings',...args);
api.getTimeForLocation = (...args) => ipcRenderer.invoke('get-time-for-location',...args);
api.getTimerRemaining = (...args) => ipcRenderer.invoke('get-timer-remaining',...args);
api.mediaControl = (...args) => ipcRenderer.invoke('media-control',...args);
api.openActionPath = (...args) => ipcRenderer.invoke('open-action-path',...args);
api.openActionUrl = (...args) => ipcRenderer.invoke('open-action-url',...args);
api.openApplicationFallback = (...args) => ipcRenderer.invoke('open-application-fallback',...args);
api.openLocalFolder = (...args) => ipcRenderer.invoke('open-local-folder',...args);
api.openUpdateRelease = (...args) => ipcRenderer.invoke('open-update-release',...args);
api.removeReminder = (...args) => ipcRenderer.invoke('remove-reminder',...args);
api.resetAllSettings = (...args) => ipcRenderer.invoke('reset-all-settings',...args);
api.runActionCommand = (...args) => ipcRenderer.invoke('run-action-command',...args);
api.saveNotebook = (...args) => ipcRenderer.invoke('save-notebook',...args);
api.searchApplications = (...args) => ipcRenderer.invoke('search-applications',...args);
api.searchFiles = (...args) => ipcRenderer.invoke('search-files',...args);
api.searchWeb = (...args) => ipcRenderer.invoke('search-web',...args);
api.setAssistantHotkey = (...args) => ipcRenderer.invoke('set-assistant-hotkey',...args);
api.setCustomActions = (...args) => ipcRenderer.invoke('set-custom-actions',...args);
api.setReminder = (...args) => ipcRenderer.invoke('set-reminder',...args);
api.setSettings = (...args) => ipcRenderer.invoke('set-settings',...args);
api.setStartup = (...args) => ipcRenderer.invoke('set-startup',...args);
api.showOpenDialog = (...args) => ipcRenderer.invoke('show-open-dialog',...args);
api.speechDiagnostics = (...args) => ipcRenderer.invoke('speech-diagnostics',...args);
api.startTimer = (...args) => ipcRenderer.invoke('start-timer',...args);
api.synthesizeEdgeTts = (...args) => ipcRenderer.invoke('synthesize-edge-tts',...args);
api.ttsBegin = (...args) => ipcRenderer.invoke('tts-begin',...args);
api.wikipediaLookup = (...args) => ipcRenderer.invoke('wikipedia-lookup',...args);
api.closeApp = (...args) => ipcRenderer.send('close-app',...args);
api.hideWindow = (...args) => ipcRenderer.send('hide-window',...args);
api.installEvaVoice = (...args) => ipcRenderer.send('install-eva-voice',...args);
api.openExternalLink = (...args) => ipcRenderer.send('open-external-link',...args);
api.openPath = (...args) => ipcRenderer.send('open-path',...args);
api.rendererError = (...args) => ipcRenderer.send('renderer-error',...args);
api.runCommand = (...args) => ipcRenderer.send('run-command',...args);
api.runSpecialCommand = (...args) => ipcRenderer.send('run-special-command',...args);
api.setSettingsVisibility = (...args) => ipcRenderer.send('set-settings-visibility',...args);
api.speechDeviceChanged = (...args) => ipcRenderer.send('speech-device-changed',...args);
api.speechStart = (...args) => ipcRenderer.send('speech-start',...args);
api.speechStop = (...args) => ipcRenderer.send('speech-stop',...args);
api.ttsEnd = (...args) => ipcRenderer.send('tts-end',...args);
api.onAccentColorUpdated = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('accent-color-updated',listener); return () => ipcRenderer.removeListener('accent-color-updated',listener); };
api.onActivateAssistant = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('activate-assistant',listener); return () => ipcRenderer.removeListener('activate-assistant',listener); };
api.onCommandFailed = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('command-failed',listener); return () => ipcRenderer.removeListener('command-failed',listener); };
api.onGoIdleAndClose = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('go-idle-and-close',listener); return () => ipcRenderer.removeListener('go-idle-and-close',listener); };
api.onOnlineSpeechStatus = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('online-speech-status',listener); return () => ipcRenderer.removeListener('online-speech-status',listener); };
api.onPlayReminderSound = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('play-reminder-sound',listener); return () => ipcRenderer.removeListener('play-reminder-sound',listener); };
api.onSettingsForceClose = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('settings-force-close',listener); return () => ipcRenderer.removeListener('settings-force-close',listener); };
api.onShowSettingsUi = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('show-settings-ui',listener); return () => ipcRenderer.removeListener('show-settings-ui',listener); };
api.onSpeechError = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('speech-error',listener); return () => ipcRenderer.removeListener('speech-error',listener); };
api.onSpeechForceStop = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('speech-force-stop',listener); return () => ipcRenderer.removeListener('speech-force-stop',listener); };
api.onSpeechResult = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('speech-result',listener); return () => ipcRenderer.removeListener('speech-result',listener); };
api.onTimerFired = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('timer-fired',listener); return () => ipcRenderer.removeListener('timer-fired',listener); };
api.onTriggerEnterAnimation = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('trigger-enter-animation',listener); return () => ipcRenderer.removeListener('trigger-enter-animation',listener); };
api.onUpdateStatus = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('update-status',listener); return () => ipcRenderer.removeListener('update-status',listener); };
api.onWakeListen = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('wake-listen',listener); return () => ipcRenderer.removeListener('wake-listen',listener); };
api.onWakeSlim = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('wake-slim',listener); return () => ipcRenderer.removeListener('wake-slim',listener); };
api.onWindowFocus = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('window-focus',listener); return () => ipcRenderer.removeListener('window-focus',listener); };
api.onWindowVisibility = callback => { const listener = (_event,...args) => callback(...args); ipcRenderer.on('window-visibility',listener); return () => ipcRenderer.removeListener('window-visibility',listener); };
api.searchSuggestions = (...args) => ipcRenderer.invoke('search-suggestions',...args);
api.releaseTtsFile = (...args) => ipcRenderer.invoke('release-tts-file',...args);
api.getTimers = (...args) => ipcRenderer.invoke('get-timers',...args);
api.mediaState = (...args) => ipcRenderer.invoke('media-state',...args);
api.getActiveTimer = (...args) => ipcRenderer.invoke('get-active-timer',...args);
api.getSpeechCapabilities = (...args) => ipcRenderer.invoke('get-speech-capabilities',...args);
api.setSetting = (...args) => ipcRenderer.invoke('set-setting',...args);
api.updateReminder = (...args) => ipcRenderer.invoke('update-reminder',...args);
api.heyCortanaToggle = (...args) => ipcRenderer.send('hey-cortana-toggle',...args);
contextBridge.exposeInMainWorld('cortana', api);
