// Browser-side compatibility layer; only named, filtered bridge operations exist.
const bridgeOperations = {
  "invoke": {
    "ask-openai": "askOpenai",
    "cancel-timer": "cancelTimer",
    "check-everything": "checkEverything",
    "check-for-updates": "checkForUpdates",
    "create-calendar-event": "createCalendarEvent",
    "eva-voice-status": "evaVoiceStatus",
    "find-application": "findApplication",
    "get-accent-color": "getAccentColor",
    "get-app-version": "getAppVersion",
    "get-edge-voices": "getEdgeVoices",
    "get-hotkey-status": "getHotkeyStatus",
    "get-notebook": "getNotebook",
    "get-reminders": "getReminders",
    "get-settings": "getSettings",
    "get-time-for-location": "getTimeForLocation",
    "get-timer-remaining": "getTimerRemaining",
    "media-control": "mediaControl",
    "open-action-path": "openActionPath",
    "open-action-url": "openActionUrl",
    "open-application-fallback": "openApplicationFallback",
    "open-local-folder": "openLocalFolder",
    "open-update-release": "openUpdateRelease",
    "remove-reminder": "removeReminder",
    "reset-all-settings": "resetAllSettings",
    "run-action-command": "runActionCommand",
    "save-notebook": "saveNotebook",
    "search-applications": "searchApplications",
    "search-files": "searchFiles",
    "search-web": "searchWeb",
    "set-assistant-hotkey": "setAssistantHotkey",
    "set-custom-actions": "setCustomActions",
    "set-reminder": "setReminder",
    "set-settings": "setSettings",
    "set-startup": "setStartup",
    "show-open-dialog": "showOpenDialog",
    "speech-diagnostics": "speechDiagnostics",
    "start-timer": "startTimer",
    "synthesize-edge-tts": "synthesizeEdgeTts",
    "tts-begin": "ttsBegin",
    "wikipedia-lookup": "wikipediaLookup",
    "search-suggestions": "searchSuggestions",
    "release-tts-file": "releaseTtsFile",
    "get-timers": "getTimers",
    "media-state": "mediaState",
    "get-active-timer": "getActiveTimer",
    "get-speech-capabilities": "getSpeechCapabilities",
    "set-setting": "setSetting",
    "update-reminder": "updateReminder"
  },
  "send": {
    "close-app": "closeApp",
    "hide-window": "hideWindow",
    "install-eva-voice": "installEvaVoice",
    "open-external-link": "openExternalLink",
    "open-path": "openPath",
    "renderer-error": "rendererError",
    "run-command": "runCommand",
    "run-special-command": "runSpecialCommand",
    "set-settings-visibility": "setSettingsVisibility",
    "speech-device-changed": "speechDeviceChanged",
    "speech-start": "speechStart",
    "speech-stop": "speechStop",
    "tts-end": "ttsEnd",
    "hey-cortana-toggle": "heyCortanaToggle"
  },
  "on": {
    "accent-color-updated": "onAccentColorUpdated",
    "activate-assistant": "onActivateAssistant",
    "command-failed": "onCommandFailed",
    "go-idle-and-close": "onGoIdleAndClose",
    "online-speech-status": "onOnlineSpeechStatus",
    "play-reminder-sound": "onPlayReminderSound",
    "settings-force-close": "onSettingsForceClose",
    "show-settings-ui": "onShowSettingsUi",
    "speech-error": "onSpeechError",
    "speech-force-stop": "onSpeechForceStop",
    "speech-result": "onSpeechResult",
    "timer-fired": "onTimerFired",
    "trigger-enter-animation": "onTriggerEnterAnimation",
    "update-status": "onUpdateStatus",
    "wake-listen": "onWakeListen",
    "wake-slim": "onWakeSlim",
    "window-focus": "onWindowFocus",
    "window-visibility": "onWindowVisibility"
  }
};
const bridgeListeners = new Map();
const ipcRenderer = {
 invoke(channel,...args) { const method=bridgeOperations.invoke[channel]; if(!method) return Promise.reject(new Error('Unknown operation')); return window.cortana[method](...args); },
 send(channel,...args) { const method=bridgeOperations.send[channel]; if(!method) throw new Error('Unknown operation'); return window.cortana[method](...args); },
 on(channel,listener) { const method=bridgeOperations.on[channel]; if(!method) throw new Error('Unknown event'); this.removeListener(channel,listener); const dispose=window.cortana[method]((...args)=>listener({},...args)); if(!bridgeListeners.has(channel))bridgeListeners.set(channel,new Map()); bridgeListeners.get(channel).set(listener,dispose); },
 removeListener(channel,listener) { bridgeListeners.get(channel)?.get(listener)?.(); bridgeListeners.get(channel)?.delete(listener); },
 emit(channel,event,...args) { for(const listener of bridgeListeners.get(channel)?.keys()||[])listener(event,...args); },
};
const path = { join: (...parts)=>parts.join('/'), basename: value=>value.split(/[\/]/).pop(), isAbsolute: value=>/^(?:[a-z]:[\/]|[\/])/i.test(value) };
const {isLoopback}=CortanaEndpoint;
const {formatShortcut}=CortanaShortcuts;
const {defaultVoice:findDefaultVoice,resolveVoice}=CortanaVoicePolicy;
