// Real Electron renderer and disposable local data. No personal lists or audio changes.
const {app,BrowserWindow,Notification}=require('electron');
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),output=path.join(root,'.verification');fs.mkdirSync(output,{recursive:true});
const reuse=process.argv.find(a=>a.startsWith('--profile='))?.slice(10);
const profile=reuse?path.resolve(reuse):fs.mkdtempSync(path.join(output,'productivity-'));
if(!profile.toLowerCase().startsWith(output.toLowerCase()+path.sep))throw Error('Only verification profiles are allowed');
const label=process.argv.find(a=>a.startsWith('--label='))?.slice(8)||'productivity';
app.setPath('userData',profile);app.setAppPath(root);app.setLoginItemSettings=()=>{throw Error('No startup changes allowed');};
Notification.prototype.show=()=>{};
if(!reuse) {
 fs.writeFileSync(path.join(profile,'settings.json'),JSON.stringify({firstRunComplete:true,firstRunRelease:'8.1.0',openAtLogin:false,heyCortana:false,isMovable:true,ttsEngine:'system'}));
 fs.writeFileSync(path.join(profile,'notebook.json'),JSON.stringify({notes:'Legacy note',introduced:true,todos:[{id:'legacy',text:'Legacy task',done:false}],profile:{name:'',home:'',work:'',weatherCity:''}}));
}
require('../main.js');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const checks=[],errors=[];
app.whenReady().then(async()=>{
 try {
  let win;for(let i=0;i<100&&!win;i++){win=BrowserWindow.getAllWindows()[0];if(!win)await delay(100);}
  if(!win)throw Error('No window');
  win.webContents.on('console-message',event=>{if(event.level==='error')errors.push(event.message);});
  await delay(5500);
  const js=code=>win.webContents.executeJavaScript('(async()=>{'+code+'})()');
  await js("window.spoken=[];speak=(text,done)=>{spoken.push(text);done?.();};Audio.prototype.play=()=>Promise.resolve();");
  const run=async(name,code)=>{
    try{const result=await js(code);checks.push({name,passed:result===true||result?.passed===true,detail:result});}
    catch(error){checks.push({name,passed:false,error:error.message});}
    console.log(checks.at(-1).passed?'PASS':'FAIL',name,checks.at(-1).passed?'':JSON.stringify(checks.at(-1)));
  };
  if(reuse) {
   await run('Lists, nickname and two timers survive process restart',"const saved=await ipcRenderer.invoke('get-notebook'),timers=await ipcRenderer.invoke('get-timers');return saved.notes==='Legacy note'&&saved.todos[0].id==='legacy'&&saved.profile.name==='Bluey'&&saved.lists[0].name==='Shopping'&&timers.length===2&&timers.every(t=>t.remaining>0);");
   await run('Recurring reminder survives restart',"return (await ipcRenderer.invoke('get-reminders')).some(r=>r.text==='Stretch'&&r.recurrence==='weekly');");
   await run('Restored timers remain independently cancellable',"const timers=await ipcRenderer.invoke('get-timers');await ipcRenderer.invoke('cancel-timer',timers[0].id);return (await ipcRenderer.invoke('get-timers')).length===1;");
  }else {
   await run('Renderer has no Node access; bridge rejects arbitrary operations and traversal',"let rejected=0;try{await ipcRenderer.invoke('arbitrary-shell');}catch{rejected++;}try{await cortana.decodeAnimation('../speech.ps1');}catch{rejected++;}return typeof require==='undefined'&&typeof process==='undefined'&&typeof cortana.invoke==='undefined'&&typeof cortana.send==='undefined'&&rejected===2&&await ipcRenderer.invoke('release-tts-file','C:/Windows/win.ini')===false;");
   await run('Named list creation preserves old Tasks and notes',"await handleListCommand('create a Shopping list');await handleListCommand('add Fresh Milk to my shopping list');const data=await ipcRenderer.invoke('get-notebook');return data.todos[0].id==='legacy'&&data.notes==='Legacy note'&&data.lists[0].items[0].text==='Fresh Milk';");
   await run('Typing and search-panel Execute update the same local list',"processQuery('add Bread to my shopping list');await new Promise(r=>setTimeout(r,150));const categories=await generateCategorizedResults('add Apples to my shopping list');showSearchPanel(categories);const item=allPanelItems.find(x=>x.el.textContent.includes('Use a built-in command'));if(!item)return {categories};item.action();await new Promise(r=>setTimeout(r,150));hideSearchPanel();return (await ipcRenderer.invoke('get-notebook')).lists[0].items.length===3;");
   await run('Exact list completion and reading retain capitalization',"await handleListCommand('mark Bread as done on my shopping list');await handleListCommand('read my shopping list');return resultsDisplay.textContent.includes('Fresh Milk')&&!spoken.at(-1).includes('Bread')&&(await ipcRenderer.invoke('get-notebook')).lists[0].items[1].done;");
   await run('Name command saves and identifies the user locally',"processQuery('call me Bluey');await new Promise(r=>setTimeout(r,150));processQuery('what is my name');await new Promise(r=>setTimeout(r,30));return notebookData.profile.name==='Bluey'&&resultsDisplay.textContent.includes('Bluey');");
   await run('Weekly voice command fills repeat form and persists',"processQuery('remind me to Stretch every Friday at 3 pm');await new Promise(r=>setTimeout(r,20));if(reminderTextInput.value!=='Stretch'||document.getElementById('reminder-repeat').value!=='weekly')return {text:reminderTextInput.value,repeat:document.getElementById('reminder-repeat').value};await onSaveReminder();return (await ipcRenderer.invoke('get-reminders')).some(r=>r.text==='Stretch'&&r.recurrence==='weekly');");
   await run('Reminder editing retains its recurrence',"const r=(await ipcRenderer.invoke('get-reminders')).find(r=>r.text==='Stretch');openNotebook('reminders');await renderNotebookReminders();document.querySelector('#notebook-reminder-list button').click();const correct=document.getElementById('reminder-repeat').value==='weekly';await onSaveReminder();return correct&&(await ipcRenderer.invoke('get-reminders')).find(x=>x.id===r.id).recurrence==='weekly';");
   await run('Named timer commands save two independent timers',"closeNotebook({immediate:true});processQuery('set a timer for 20 minutes named Tea');await new Promise(r=>setTimeout(r,200));processQuery('set a timer for 30 minutes named Oven');await new Promise(r=>setTimeout(r,200));const timers=await ipcRenderer.invoke('get-timers');return timers.length===2&&timers[0].label==='Tea'&&timers[1].label==='Oven';");
   await run('Invalid timer and ambiguous cancellation retain both timers',"await startTimer(1000,'hours',3600000000);await cancelNamedTimer('');return (await ipcRenderer.invoke('get-timers')).length===2&&document.querySelectorAll('.reminder-list-item').length===2;");
   await run('My day uses the Notebook page with nickname, tasks and running timers',"await showMyDay();const day=document.getElementById('notebook-day');return {passed:!day.hidden&&document.getElementById('notebook-title').textContent==='My day'&&day.textContent.includes('Bluey')&&day.textContent.includes('Fresh Milk')&&day.textContent.includes('Tea')&&day.textContent.includes('Legacy task')&&!resultsDisplay.classList.contains('day-summary'),hidden:day.hidden,title:document.getElementById('notebook-title').textContent,text:day.textContent,request:assistantRequestGeneration,page:notebookPage};");
   await run('List fields and task rows share flat Cortana controls',"openNotebook('todos');const fields=['list-name','todo-text','notebook-name'].map(id=>getComputedStyle(document.getElementById(id)));const checkbox=getComputedStyle(document.querySelector('.todo-item input'));return fields.every(s=>s.backgroundColor==='rgb(23, 23, 23)'&&s.borderRadius==='0px'&&s.fontSize==='15px'&&s.fontFamily.includes('Segoe UI'))&&checkbox.width==='20px'&&checkbox.borderRadius==='0px';");
   await run('Long list names and tasks wrap without covering their delete controls',"const previous=notebookData,selection=selectedListId;try{notebookData=structuredClone(previous);const result=CortanaLists.apply(notebookData,{action:'create',name:'L'.repeat(80)},()=>crypto.randomUUID());selectedListId=result.listId;notebookData.lists.find(list=>list.id===selectedListId).items.push({id:'long',text:'W'.repeat(512),done:false});renderTodos();await new Promise(r=>setTimeout(r,350));const heading=document.getElementById('list-heading').getBoundingClientRect(),remove=document.getElementById('delete-list').getBoundingClientRect(),label=document.querySelector('.todo-item label').getBoundingClientRect(),itemButton=document.querySelector('.todo-item button').getBoundingClientRect(),pane=document.querySelector('.notebook-content');return {passed:heading.right<=remove.left&&label.right<=itemButton.left&&pane.scrollWidth===pane.clientWidth,heading:heading.toJSON(),remove:remove.toJSON(),label:label.toJSON(),itemButton:itemButton.toJSON(),width:pane.clientWidth,scrollWidth:pane.scrollWidth};}finally{notebookData=previous;selectedListId=selection;renderTodos();}");
   await js("openNotebook('todos');document.querySelector('.todo-item input').focus();");
   win.webContents.sendInputEvent({type:'keyDown',keyCode:'Space'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Space'});await delay(150);
   await run('Keyboard Space checks and saves a task through the real control',"return document.querySelector('.todo-item input').checked&&(await ipcRenderer.invoke('get-notebook')).lists[0].items[0].done;");
   win.webContents.sendInputEvent({type:'keyDown',keyCode:'Space'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Space'});await delay(150);
   await run('Empty My day and read failures use clear page states',"const original=ipcRenderer.invoke,previous=notebookData;try{notebookData={...notebookData,todos:[],lists:[]};ipcRenderer.invoke=(channel,...args)=>['get-reminders','get-timers'].includes(channel)?Promise.resolve([]):original.call(ipcRenderer,channel,...args);await showMyDay();const empty=document.getElementById('notebook-day-content').textContent;ipcRenderer.invoke=(channel,...args)=>channel==='get-timers'?Promise.reject(Error('Unavailable')):original.call(ipcRenderer,channel,...args);await showMyDay();return empty.includes('No reminders today.')&&empty.includes('All clear.')&&empty.includes('No timers running.')&&document.getElementById('notebook-day-status').textContent.includes(\"couldn't load your day\");}finally{ipcRenderer.invoke=original;notebookData=previous;}");
   await js("await showMyDay();");await delay(350);
   fs.writeFileSync(path.join(output,label+'-day.png'),(await win.webContents.capturePage()).toPNG());
   await run('Hiding My day resets Home without leaving the smaller summary font',"ipcRenderer.emit('go-idle-and-close',{});await new Promise(r=>setTimeout(r,350));return !document.getElementById('notebook-sidebar').classList.contains('visible')&&getComputedStyle(resultsDisplay).fontSize==='28px'&&resultsDisplay.textContent.length>0;");
   win.show();win.focus();win.webContents.send('trigger-enter-animation',{timeSinceHidden:6000});await delay(500);
   await run('Reopening Home after My day restores normal text and the running timer',"return document.getElementById('navigation-home').getAttribute('aria-current')==='page'&&!document.getElementById('notebook-sidebar').classList.contains('visible')&&getComputedStyle(resultsDisplay).fontSize==='28px'&&getComputedStyle(resultsDisplay.querySelector('#timer-display')).fontSize==='24px';");
   await run('The Home greeting stays at its original size after visiting My day',"const previous=timerEndTime;try{timerEndTime=null;setStateIdle();return getComputedStyle(resultsDisplay).fontSize==='28px'&&getComputedStyle(resultsDisplay.querySelector('p')).fontSize==='28px'&&resultsDisplay.textContent===getIdleMessage();}finally{timerEndTime=previous;setStateIdle();}");
   await run('A late My day load cannot replace a newer Notebook page or speak over it',"const original=ipcRenderer.invoke;let release;ipcRenderer.invoke=(channel,...args)=>channel==='get-timers'?new Promise(r=>release=r):original.call(ipcRenderer,channel,...args);try{const before=spoken.length,pending=showMyDay();openNotebook('notes');release([]);await pending;return notebookPage==='notes'&&document.getElementById('notebook-day-content').childElementCount===0&&spoken.length===before;}finally{ipcRenderer.invoke=original;closeNotebook({immediate:true});}");
   await run('Native audio state reads without changing playback or volume',"const state=await ipcRenderer.invoke('media-state');return {passed:state.success&&state.volume>=0&&state.volume<=100&&typeof state.muted==='boolean',...state};");
   await run('Search slides without fading and scrolls above expanded input',"setStateActive();searchBar.disabled=false;searchBar.value='A long query\\nAnother line\\nA third line';searchBar.style.height='105px';await new Promise(r=>setTimeout(r,50));showSearchPanel([{name:'Results',items:Array.from({length:30},(_,i)=>({title:'Result '+i,subtitle:'Sample',icon:'app',action:()=>{}}))}]);await new Promise(r=>setTimeout(r,40));const early=getComputedStyle(searchPanel),earlyTransform=early.transform,opacity=early.opacity;await new Promise(r=>setTimeout(r,280));const box=document.querySelector('.search-container').getBoundingClientRect(),panel=searchPanel.getBoundingClientRect();selectedPanelIndex=29;updatePanelSelection();return {passed:opacity==='1'&&earlyTransform!=='none'&&panel.bottom<=box.top+1&&searchPanel.scrollTop>0&&document.querySelector('.search-container').getBoundingClientRect().top===box.top,earlyTransform,panel:panel.toJSON(),box:box.toJSON()};");
   fs.writeFileSync(path.join(output,label+'-search.png'),(await win.webContents.capturePage()).toPNG());
   await run('Search close and rapid reopen retain focus boundaries',"hideSearchPanel();if(!searchPanel.inert)return false;showSearchPanel([{name:'Sample',items:[{title:'Reopen',icon:'app',action:()=>{}}]}]);await new Promise(r=>setTimeout(r,300));const visible=getComputedStyle(searchPanel).visibility==='visible';hideSearchPanel();return visible&&searchPanel.inert;");
   await run('Late search suggestions cannot reopen over the Notebook',"const original=generateCategorizedResults;let release;generateCategorizedResults=()=>new Promise(r=>release=r);try{searchBar.value='Pending search';searchBar.disabled=false;const pending=onSearchInput();openNotebook();release([{name:'Late',items:[{title:'Old query',icon:'app',action:()=>{}}]}]);await pending;return !searchPanel.classList.contains('visible')&&searchPanel.inert;}finally{generateCategorizedResults=original;closeNotebook({immediate:true});}");
   await run('Native volume assignments repeat safely at the existing level and mute state',"const before=await ipcRenderer.invoke('media-state');if(!before.success)return before;const action=before.muted?'mute':'unmute';const first=await ipcRenderer.invoke('media-control',action),second=await ipcRenderer.invoke('media-control',action);const level=await ipcRenderer.invoke('media-control',{action:'setvolume',level:before.volume});const after=await ipcRenderer.invoke('media-state');return {passed:first.success&&second.success&&level.success&&after.muted===before.muted&&Math.abs(after.volume-before.volume)<0.1,before,after};");
   await run('Read a named list through Tasks aliases without intercepting other commands',"return CortanaLists.find(notebookData,'to-do').id==='tasks'&&CortanaLists.parse('explain linked lists')===null;");
   await js("clearSearchBar();searchBar.style.height='';openNotebook('todos');selectedListId=notebookData.lists[0].id;renderTodos();");await delay(350);
   fs.writeFileSync(path.join(output,label+'-lists.png'),(await win.webContents.capturePage()).toPNG());
   await js("closeNotebook({immediate:true});setStateActive();await showMyDay();");await delay(300);
   fs.writeFileSync(path.join(output,label+'-day.png'),(await win.webContents.capturePage()).toPNG());
  }
  fs.writeFileSync(path.join(output,label+'.json'),JSON.stringify({profile,checks,errors},null,2));
  console.log('PRODUCTIVITY_RESULT',JSON.stringify({passed:checks.filter(c=>c.passed).length,total:checks.length,errors}));
  app.exit(checks.every(c=>c.passed)&&!errors.length?0:1);
 }catch(error){console.error(error);app.exit(1);}
});
setTimeout(()=>app.exit(1),90000).unref();
